### ISSUE TITLE
Should the url format be so strict?

### ISSUE THREAD

**Issue by renarsvilnis** [gajus/url-regexp#5]
Should the url format be so strict? 

Would like to know your thoughts on some topics/questions before fixing issues:
1. **Make protocol identifiers optional?** It would add more versatility, then urls such as `www.twitter.com` would be matched, but as right now domain hosts are also optional it would create false positives.
2. **Add option for filtering IP address**, rather then doing it by default. Would add additional use-cases for the module.
3. **Return a valid url from a invalid url string.** By that mean the regex should be forgiving for such examples as listed below.
`http://1.1.1.1.1` => `http://1.1.1.1`
`http://www.foo.bar./` => `http://www.foo.bar`

**Comment by gajus** [comment]
I am happy with the first two proposal if these are configurable options.

I don't understand the last suggestion.

**Comment by renarsvilnis** [comment]
I can make the first two configurable.

By the third one I mean a situation: a user wants fetch urls from the string. The string contains a invalid url such as `http://1.1.1.1.1`, but the matcher would find and return `http://1.1.1.1` which is a valid url. This can be also added as an option.

I see your added `pragmatist` and converted to ES6, thats very good. Does `pragmatist` include any transpiling such as babel?

**Comment by gajus** [comment]
> I see your added pragmatist and converted to ES6, thats very good. Does pragmatist include any transpiling such as babel?

Yes, `pragmatist` is just an abstraction of Babel, ESLint and other common tools used in the build process.

**Comment by gajus** [comment]
> By the third one I mean a situation: a user wants fetch urls from the string. The string contains a invalid url such as http://1.1.1.1.1, but the matcher would find and return http://1.1.1.1 which is a valid url. This can be also added as an option.

If it is optional, of course.

**Comment by renarsvilnis** [comment]
Ok, will put a pull request in the upcoming days.
